language: node_js
node_js:
  - "6.12"
  - "8.9"
  - "9.1"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

addons:
  chrome: stable

before_install:
  google-chrome-stable --headless
